# Generated by Django 3.2.9 on 2022-03-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='verified',
        ),
    ]
